version: '3'
services:
  app:
    build: app
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./app/static:/usr/src/app/static
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./db:/data/db
  fake_drone1:
    build: fake_drone
    restart: unless-stopped
    depends_on:
      - "mongo"
      - "app"
    environment:
      - "DRONE_ID=1"
  fake_drone2:
    build: fake_drone
    restart: unless-stopped
    depends_on:
      - "mongo"
      - "app"
    environment:
      - "DRONE_ID=2"
  fake_drone3:
    build: fake_drone
    restart: unless-stopped
    depends_on:
      - "mongo"
      - "app"
    environment:
      - "DRONE_ID=3"
  fake_drone4:
    build: fake_drone
    restart: unless-stopped
    depends_on:
      - "mongo"
      - "app"
    environment:
      - "DRONE_ID=4"
