version: '3'
services:
  app:
    build: app
    ports:
      - "5000:5000"
    restart: unless-stopped
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./db:/data/db
  rosmaster:
    build: ros
  ros_fake_gps:
    build: ros_fake_gps
    environment:
      - "ROS_HOSTNAME=ros_fake_gps"
      - "ROS_MASTER_URI=http://rosmaster:11311"
      - "ROS_PACKAGE_PATH=/usr/src/app/fake_gps:$ROS_PACKAGE_PATH"
  ros_print_to_gcs:
    build: ros_print_to_gcs
    environment:
      - "ROS_HOSTNAME=ros_print_to_gcs"
      - "ROS_MASTER_URI=http://rosmaster:11311"
      - "ROS_PACKAGE_PATH=/usr/src/app/print_to_gcs:$ROS_PACKAGE_PATH"
